### ISSUE TITLE
the code question

### ISSUE THREAD

**Issue by woaixueyingying** [ma-xu/Context-Cluster#7]
![image](https://user-images.githubusercontent.com/123790176/226495935-118afc5d-9f37-4c4f-ae40-c292a0d598aa.png)
![image](https://user-images.githubusercontent.com/123790176/226510417-45cd1880-2cab-4287-8461-239cea4fc84f.png)

C in the formula for the aggregated feature G is denoted by 'mask' in the code, why is it not denoted by 'sim' at the beginning.

**Comment by YangTracy** [comment]
Yes, I also have the same question. The 'mask' in the code should be 'sim'. Maybe the code makes a mistake here.

**Comment by ma-xu** [comment]
@YangTracy @woaixueyingying Thanks very much for the detailed question. I will double-check it and reply by this week.

**Comment by YangTracy** [comment]
您发给我的邮件我已经收到了，谢谢！

**Comment by 1chizhang** [comment]
I also found this problem, so what exactly is happening and what effect would replacing c with the sim in eq cause?

**Comment by ma-xu** [comment]
@YangTracy @Volodymyr233 @woaixueyingying 

Thanks for this issue! 

Double-check with co-authors, this is a small bug, no influence to our conclusions and contributions. 
We re-trained coc-tiny on ImageNet1k with same settings and achieved 72.2, an improvement of 0.4 (reported 71.8).

The slight improvement can be contributed to the soft/weighted summation, instead of mask (cn be considered as a hard version of C in Eq. 1). 

We will updated all checkpoints once we finished re-training all models. Again, thanks for your kind reminder.
